//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarResonanceDpsAnalysis.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("星痕共鸣DPS统计.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg t=&quot;1754553843272&quot; class=&quot;icon&quot; viewBox=&quot;0 0 1024 1024&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; p-id=&quot;7228&quot; width=&quot;200&quot; height=&quot;200&quot;&gt;&lt;path d=&quot;M308.705882 124.235294c100.291765 0 184.470588 37.406118 184.470589 96.617412v210.823529c0 59.211294-84.208941 96.647529-184.470589 96.64753-97.581176 0-179.892706-35.448471-184.289882-91.858824l-0.180706-4.788706v-210.823529l0.180706-4.728471c4.397176-56.470588 86.738824-91.888941 184.289882-91.888941z m0 298.676706c-51.109647 0-98.032941-9.728-131.76470 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string data_display {
            get {
                return ResourceManager.GetString("data-display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg t=&quot;1754553927035&quot; class=&quot;icon&quot; viewBox=&quot;0 0 1096 1024&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; p-id=&quot;9938&quot; width=&quot;200&quot; height=&quot;200&quot;&gt;&lt;path d=&quot;M890.591549 699.363155l-27.373972 11.826479-134.25938 11.047662c-3.374873-1.413408-6.720901-2.797972-10.038084-4.15369l-38.594705-10.542874a42.128225 42.128225 0 0 1-12.792788-5.942084c-22.35493-15.388845-37.628394-45.690592-52.555719-78.025916l-1.874929-4.081577a42.15707 42.15707 0 0 1-2.16338-5.682479c0-0.05769-0.043268-0.100958-0.057691-0.17307-0.40383 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string userUid {
            get {
                return ResourceManager.GetString("userUid", resourceCulture);
            }
        }
    }
}
